import CarouselManager from "../CarouselManager.js";

const c1 = new CarouselManager({
  itemWidth: 150,
  itemHeight: 75,
  itemSpacing: 10,
  buttonWidth: "25px",
  buttonHeight: "75%",
  buttonPosition: "center",
  numItemsVisible: 4,
  scrollBy: 4,
  containerID: "carousel-1",
  resizingMethod: "stretch-scale",
  transitionDuration: 750,
  transitionDelay: 0,
  transitionTimingFunction: "ease-in-out",
  scrollable: true,
  wrappingMethod: "none",
});

const c2 = new CarouselManager({
  itemWidth: 150,
  itemHeight: 75,
  itemSpacing: 10,
  buttonWidth: "25px",
  buttonHeight: "75%",
  buttonPosition: "center",
  numItemsVisible: 4,
  scrollBy: 4,
  containerID: "carousel-2",
  resizingMethod: "stretch-scale",
  transitionDuration: 750,
  transitionDelay: 0,
  transitionTimingFunction: "ease-in-out",
  scrollable: true,
  wrappingMethod: "wrap-simple",
});

const c3 = new CarouselManager({
  itemWidth: 150,
  itemHeight: 75,
  itemSpacing: 10,
  buttonWidth: "25px",
  buttonHeight: "75%",
  buttonPosition: "center",
  numItemsVisible: 4,
  scrollBy: 4,
  containerID: "carousel-3",
  resizingMethod: "stretch-scale",
  transitionDuration: 750,
  transitionDelay: 0,
  transitionTimingFunction: "ease-in-out",
  scrollable: true,
  wrappingMethod: "wrap-smart",
});
